version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/test -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db
  api:
    build:
      context: ./api
      dockerfile: dockerfile.local
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - flyway
volumes:
  db:
