name: Test Secret

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "my secret is: $SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
      - run: "cat key"
