name: Test PR Database

on:
  pull_request:
    branches:
      - main
    paths:
      - "database/**"

defaults:
  run:
    working-directory: ./database

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: execute flyway in docker 🐳
        run: docker-compose up --abort-on-container-exit
