name: Test PR API

on:
  pull_request:
    paths:
      - "api/**"

defaults:
  run:
    working-directory: ./api

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm i
      - name: Test
        run: npm run test
