name: Test PR

on: [push]

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - run: echo '🎉 The test secret "$SECRET_VALUE"'
        env:
          SECRET_VALUE: ${{ secrets.SECRET_VALUE }}
