name: Test PR

on: [push]

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
      - run: "cat key"
